import { config } from "dotenv";
config();

const {
  PORT,
  NODE_ENV,
  POSTGRES_USER,
  POSTGRES_HOST,
  POSTGRES_DATABASE,
  POSTGRES_PASSWORD,
  POSTGRES_PORT,
  SALT_ROUNDS,
  JWT_SECRET,
} = process.env;

export const Config = {
  PORT,
  NODE_ENV,
  POSTGRES_USER,
  POSTGRES_HOST,
  POSTGRES_DATABASE,
  POSTGRES_PASSWORD,
  POSTGRES_PORT,
  SALT_ROUNDS,
  JWT_SECRET,
};
