import { config } from "dotenv";
config();

const {
  PORT,
  POSTGRES_USER,
  POSTGRES_HOST,
  POSTGRES_DATABASE,
  POSTGRES_PASSWORD,
  POSTGRES_PORT,
  SALT_ROUNDS,
} = process.env;

export const Config = {
  PORT,
  POSTGRES_USER,
  POSTGRES_HOST,
  POSTGRES_DATABASE,
  POSTGRES_PASSWORD,
  POSTGRES_PORT,
  SALT_ROUNDS,
};
